import http from 'http';
import app from '../src/app';
import { prisma } from '../src/lib/prisma';
import { Role } from '@prisma/client';

const PORT = 5005;
const BASE_URL = `http://localhost:${PORT}/api`;

interface TestResponse {
  status: number;
  body: any;
}

async function request(
  path: string,
  method: 'GET' | 'POST',
  body?: any,
  token?: string
): Promise<TestResponse> {
  return new Promise((resolve, reject) => {
    const url = new URL(BASE_URL + path);
    const payload = body ? JSON.stringify(body) : null;

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };

    if (payload) {
      headers['Content-Length'] = Buffer.byteLength(payload).toString();
    }

    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
    }

    const req = http.request(
      url,
      {
        method,
        headers,
      },
      (res) => {
        let data = '';
        res.on('data', (chunk) => (data += chunk));
        res.on('end', () => {
          try {
            const parsed = data ? JSON.parse(data) : {};
            resolve({ status: res.statusCode || 500, body: parsed });
          } catch {
            resolve({ status: res.statusCode || 500, body: data });
          }
        });
      }
    );

    req.on('error', reject);

    if (payload) {
      req.write(payload);
    }
    req.end();
  });
}

function assert(condition: boolean, message: string) {
  if (!condition) {
    console.error(`❌ FAIL: ${message}`);
    process.exit(1);
  } else {
    console.log(`✅ PASS: ${message}`);
  }
}

async function runSymptomLLMTests() {
  console.log('🚀 Starting Pre-Visit Symptom Form Intake & LLM Processing Tests...\n');

  const server = app.listen(PORT);

  try {
    const doctorEmail = 'dr.cardio.llm@healthcare.com';
    const patientEmail1 = 'patient.llm1@healthcare.com';
    const patientEmail2 = 'patient.llm2@healthcare.com';

    // Cleanup existing test data
    await prisma.user.deleteMany({
      where: { email: { in: [doctorEmail, patientEmail1, patientEmail2] } },
    });

    // 1. Create Doctor Profile
    const doctorReg = await request('/auth/register', 'POST', {
      email: doctorEmail,
      password: 'DoctorPassword123!',
      name: 'Dr. Elizabeth Blackwell',
      role: 'DOCTOR',
      specialisation: 'Cardiology',
      slotDurationMinutes: 30,
      workingHours: {
        wednesday: { start: '09:00', end: '17:00' },
      },
    });
    assert(doctorReg.status === 201, 'Doctor profile created');
    const doctorProfileId = doctorReg.body.user.doctorProfile.id;

    // 2. Register Patient 1
    const patient1Reg = await request('/auth/register', 'POST', {
      email: patientEmail1,
      password: 'PatientPassword123!',
      name: 'Arthur Patient',
      role: 'PATIENT',
    });
    const patient1Token = patient1Reg.body.token;

    // --- TEST 1: Symptom Form Intake with AI Analysis ---
    console.log('\n--- Test Suite 1: Booking with Symptom Form & AI Analysis ---');
    const slotTime1 = '2026-09-16T09:00:00.000Z'; // 2026-09-16 is a Wednesday
    const symptomsText = 'I have experienced sharp chest discomfort and mild dizziness for the past 2 hours.';

    const book1Res = await request(
      '/appointments',
      'POST',
      {
        doctorId: doctorProfileId,
        slotStartTime: slotTime1,
        symptoms: symptomsText,
      },
      patient1Token
    );

    assert(book1Res.status === 201, 'Booking succeeds with 201 Created');
    assert(!!book1Res.body.appointment.symptomForm, 'SymptomForm record attached to booking response');
    const sf = book1Res.body.appointment.symptomForm;
    assert(sf.rawSymptoms === symptomsText, 'rawSymptoms saved correctly');
    assert(sf.urgencyLevel === 'HIGH', 'LLM correctly determined HIGH urgency level for chest discomfort');
    assert(!!sf.chiefComplaint, 'chiefComplaint generated by LLM');
    assert(Array.isArray(sf.suggestedQuestions) && sf.suggestedQuestions.length >= 1, 'Suggested questions generated');
    assert(!!sf.llmProcessedAt, 'llmProcessedAt timestamp populated upon LLM success');

    // --- TEST 2: Symptom Intake Fallback Resilience ---
    console.log('\n--- Test Suite 2: Fallback Resilience on Raw Symptoms ---');
    // Register Patient 2
    const patient2Reg = await request('/auth/register', 'POST', {
      email: patientEmail2,
      password: 'PatientPassword123!',
      name: 'Bob Patient',
      role: 'PATIENT',
    });
    const patient2Token = patient2Reg.body.token;

    const slotTime2 = '2026-09-16T09:30:00.000Z';
    const book2Res = await request(
      '/appointments',
      'POST',
      {
        doctorId: doctorProfileId,
        slotStartTime: slotTime2,
        symptoms: 'Mild skin itchiness after using new soap.',
      },
      patient2Token
    );

    assert(book2Res.status === 201, 'Booking succeeds even under fallback symptom intake');
    assert(book2Res.body.appointment.symptomForm.urgencyLevel === 'LOW', 'Correctly assessed LOW urgency for mild itchiness');

    console.log('\n🎉 ALL PRE-VISIT SYMPTOM FORM & LLM TESTS PASSED SUCCESSFULLY!');
  } finally {
    server.close();
    await prisma.$disconnect();
  }
}

runSymptomLLMTests().catch((err) => {
  console.error('Fatal Symptom LLM Test Execution Error:', err);
  process.exit(1);
});
